### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rafaelomodei** [rafaelomodei/algoritimo-genetico-fsi#1]
- [x] Criar repositório
- [x] Criar Checklist
- [x] Criar base de dados (Json da disciplina) 
- [x] Fazer a leitura da base de dados
- [x] Montar objeto com as disciplinas
- [x] Criar o primeiro cromossomos
- [x] Gerar população inicial
- [x] Verificar se as disciplinas têm conflitos
- [x] Verificar se os professores têm conflitos
- [x] Verificar a ordenação das dependências das disciplinas
- [ ] Classificar os elementos da população
- [ ] Verificar se atingiu o objetivo
- [ ] Gerar nova população cruzamento/mutação
- [ ] Apresentar o resultado
